# Pair Wise Percolation Between 2 nodes

Import python modules and the edges of the network for which we are going to compute the percolation properties.

In [76]:
import numpy as np
from CCD_class import CCD, Newman_Ziff_algorithm
import os
from functools import reduce

In [77]:
fn_net = 'double_triangle.txt'
path_net = os.path.join('/Users/joanpont/Desktop/Master/MasterThesis/Networks/', fn_net)
edges = np.sort(np.loadtxt(path_net,int), axis=1)

We initialize the CCDs of all the edges:

In [89]:
ls_CCDs = [CCD(nodes=edge, ls_roots=[(np.min(edge),np.min(edge)), 
                                    (np.min(edge),np.max(edge))]) for edge in edges]

We define an elimination order and we delete the nodes for which we are computing $p_{ij}$, e.g. $i=1$ and $j=6$.

In [90]:
i,j = 1,6
ls_elimination = [5,6,4,3,2,1]
ls_elimination = [node for node in ls_elimination if node not in [1,6]]

In [80]:
for node in ls_elimination:
    CCDs_node = [x for x in ls_CCDs if node in x._nodes] 
    reduce((lambda x, y: x.multiply(y)), CCDs_node)
    CCDs_node[0].remove_node(node)
    for x in CCDs_node[1:]:
        x.delete_CCD() 

AttributeError: 'NoneType' object has no attribute 'multiply'

In [85]:
reduce((lambda x, y: x.multiply(y)), CCDs_node)

AttributeError: 'NoneType' object has no attribute 'multiply'

In [83]:
for i in range(7):
    print(ls_CCDs[i]._nodes)

[1 2]
[2 3]
[1 3]
[1 4 6]
[4 6]
[4 6]
[0]


In [95]:
node = 4
CCDs_node = [x for x in ls_CCDs if node in x._nodes] 

In [68]:
CCDs_node[0]._nodes

array([1, 4, 6])

In [70]:
ls_CCDs

In [73]:
reduce((lambda x, y: x.multiply(y)), CCDs_node[1:], CCDs_node[0])

AttributeError: 'NoneType' object has no attribute 'multiply'

In [75]:
y

NameError: name 'y' is not defined

In [96]:
reduce((lambda x, y: x.multiply(y)), CCDs_node)
CCDs_node[0].remove_node(node)
for x in CCDs_node[1:]:
    x.delete_CCD() 

AttributeError: 'NoneType' object has no attribute 'multiply'

In [98]:
CCD1 = ls_CCDs[0]

In [99]:
CCD1.

<function CCD.__reduce__>

In [97]:
for CCD in ls_CCDs:
    print(CCD._nodes, CCD._roots,  CCD._probabilities, CCD._sizes)

[1 2] {(1, 1): array([1]), (1, 2): array([1, 2])} {(1, 1): array([ 0.  ,  0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,
        0.09,  0.1 ,  0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,
        0.18,  0.19,  0.2 ,  0.21,  0.22,  0.23,  0.24,  0.25,  0.26,
        0.27,  0.28,  0.29,  0.3 ,  0.31,  0.32,  0.33,  0.34,  0.35,
        0.36,  0.37,  0.38,  0.39,  0.4 ,  0.41,  0.42,  0.43,  0.44,
        0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ,  0.51,  0.52,  0.53,
        0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ,  0.61,  0.62,
        0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ,  0.71,
        0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ,
        0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,
        0.9 ,  0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,
        0.99,  1.  ]), (1, 2): array([ 1.  ,  0.99,  0.98,  0.97,  0.96,  0.95,  0.94,  0.93,  0.92,
        0.91,  0.9 ,  0.89,  0.88,  0.87,  0.86,  0.85,  0.84,  0.83,


In [45]:
CCDs_nodes[2]

NameError: name 'CCDs_nodes' is not defined

In [38]:
reduce((lambda x, y: x.multiply(y)), CCDs_node)

AttributeError: 'NoneType' object has no attribute 'multiply'

In [35]:
x

In [36]:
y

NameError: name 'y' is not defined

In [31]:
None in CCDs_node

True

In [11]:
for x in CCDs_node[1:]:
    x.delete_CCD() 

In [16]:
CCDs_node[1]._nodes

array([ 0.])

In [28]:
CCDs_node[0]._probabilities

{(4, 4): array([  0.00000000e+00,   1.00000000e-04,   4.00000000e-04,
          9.00000000e-04,   1.60000000e-03,   2.50000000e-03,
          3.60000000e-03,   4.90000000e-03,   6.40000000e-03,
          8.10000000e-03,   1.00000000e-02,   1.21000000e-02,
          1.44000000e-02,   1.69000000e-02,   1.96000000e-02,
          2.25000000e-02,   2.56000000e-02,   2.89000000e-02,
          3.24000000e-02,   3.61000000e-02,   4.00000000e-02,
          4.41000000e-02,   4.84000000e-02,   5.29000000e-02,
          5.76000000e-02,   6.25000000e-02,   6.76000000e-02,
          7.29000000e-02,   7.84000000e-02,   8.41000000e-02,
          9.00000000e-02,   9.61000000e-02,   1.02400000e-01,
          1.08900000e-01,   1.15600000e-01,   1.22500000e-01,
          1.29600000e-01,   1.36900000e-01,   1.44400000e-01,
          1.52100000e-01,   1.60000000e-01,   1.68100000e-01,
          1.76400000e-01,   1.84900000e-01,   1.93600000e-01,
          2.02500000e-01,   2.11600000e-01,   2.20900000e-01,


In [34]:
ls_CCDs[]._probabilities

{(4, 4): array([ 0.  ,  0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,
         0.09,  0.1 ,  0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,
         0.18,  0.19,  0.2 ,  0.21,  0.22,  0.23,  0.24,  0.25,  0.26,
         0.27,  0.28,  0.29,  0.3 ,  0.31,  0.32,  0.33,  0.34,  0.35,
         0.36,  0.37,  0.38,  0.39,  0.4 ,  0.41,  0.42,  0.43,  0.44,
         0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ,  0.51,  0.52,  0.53,
         0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ,  0.61,  0.62,
         0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ,  0.71,
         0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ,
         0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,
         0.9 ,  0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,
         0.99,  1.  ]),
 (4, 6): array([ 1.  ,  0.99,  0.98,  0.97,  0.96,  0.95,  0.94,  0.93,  0.92,
         0.91,  0.9 ,  0.89,  0.88,  0.87,  0.86,  0.85,  0.84,  0.83,
         0.82,  0.81,  0.8 ,  0.79,  

In [5]:
reduce((lambda x, y: x*y), [1,2,3,4])

24

In [9]:
CCD(np.zeros(1), [np.zeros(1)])

TypeError: unhashable type: 'numpy.ndarray'

In [ ]:
self._roots = {roots: np.array(sorted(set(roots))) for roots in ls_roots}